#!/usr/bin/env python
# coding: utf8
from gluon import *
punct = ['.', ',', '!', '?', '—']
partos = ['NOUN', 'ADJF', 'ADJS', 'VERB', 'INFN', 'GRND', 'PRTF', 'PRTS', 'ADVB', 'PREP', 'CONJ', 'NPRO', 'PRCL']
animacy = ['None', 'anim', 'inan']
gender = ['None', 'masc', 'femn', 'neut', 'Ms-f']
number = ['None', 'sing', 'plur', 'Sgtm', 'Pltm']
case = ['None', 'nomn', 'gent', 'datv', 'accs', 'ablt', 'loct', 'voct', 'gen1', 'gen2', 'acc2', 'loc1', 'loc2']
aspect = ['None', 'perf', 'impf']
trans = ['None', 'tran', 'intr']
person = ['None', '1per', '2per', '3per']
tenses = ['None', 'past', 'pres', 'futr']
mood = ['None', 'indc', 'impr']
voice = ['None', 'actv', 'pssv']
names = ['None', 'Abbr', 'Name', 'Surn', 'Patr', 'Geox', 'Init']
style = ['None', 'Infr', 'Slng', 'Arch', 'Litr', 'Erro', 'Dist']
other = ['Ques', 'Dmns', 'Prnt', 'Prdx', 'Af-p', 'Anph', 'Inmx', 'V-be', 'V-en', 'V-ie', 'V-bi', 'V-ey', 'V-oy', 'Cmp2', 'V-ej', 'Fimp', 'Coun', 'Coll', 'V-sh', 'Vpre', 'Supr', 'Qual', 'Apro', 'Anum', 'Poss']
ypartos = ['A', 'ADV', 'ADVPRO', 'ANUM', 'APRO', 'COM', 'CONJ', 'INTJ', 'NUM', 'PART', 'PR', 'S', 'SPRO', 'V']
ytense = ['tense', 'praes',	'inpraes', 'praet']
ycase = ['cas', 'nom', 'gen',	'dat', 'acc', 'ins', 'abl', 'part', 'loc', 'voc']
ynum = ['number', 'sg', 'pl']
yverb = ['verb', 'ger', 'inf', 'partcp', 'indic', 'imper']
yform = ['forma', 'brev', 'plen', 'poss']
ycomp = ['comp', 'supr', 'comp']
yperson = ['person', '1p', '2p', '3p']
ygender = ['gender', 'm', 'f', 'n']
yaspect = ['aspect', 'ipf', 'pf']
yvoice = ['voice', 'act', 'pass']
yanim = ['anim', 'anim', 'inan']
ytrans = ['trans', 'tran', 'intr']
yother = ['other', 'parenth', 'geo', 'awkw', 'persn', 'dist', 'mf', 'obsc', 'patrn', 'praed', 'inform', 'rare', 'abbr', 'obsol', 'famn']
all_parts = [ytense, ycase, ynum, yverb, yform, ycomp, yperson, ygender, yaspect, yvoice, yanim, ytrans, yother]
def c(a):
    punct = ['.', ',', '!', '?', '—']
    partos = ['NOUN', 'ADJF', 'ADJS', 'VERB', 'INFN', 'GRND', 'PRTF', 'PRTS', 'ADVB', 'PREP', 'CONJ', 'NPRO', 'PRCL']
    animacy = ['None', 'anim', 'inan']
    gender = ['None', 'masc', 'femn', 'neut', 'Ms-f']
    number = ['None', 'sing', 'plur', 'Sgtm', 'Pltm']
    case = ['None', 'nomn', 'gent', 'datv', 'accs', 'ablt', 'loct', 'voct', 'gen1', 'gen2', 'acc2', 'loc1', 'loc2']
    aspect = ['None', 'perf', 'impf']
    trans = ['None', 'tran', 'intr']
    person = ['None', '1per', '2per', '3per']
    tenses = ['None', 'past', 'pres', 'futr']
    mood = ['None', 'indc', 'impr']
    voice = ['None', 'actv', 'pssv']
    names = ['None', 'Abbr', 'Name', 'Surn', 'Patr', 'Geox', 'Init']
    style = ['None', 'Infr', 'Slng', 'Arch', 'Litr', 'Erro', 'Dist']
    other = ['Ques', 'Dmns', 'Prnt', 'Prdx', 'Af-p', 'Anph', 'Inmx', 'V-be', 'V-en', 'V-ie', 'V-bi', 'V-ey', 'V-oy', 'Cmp2', 'V-ej', 'Fimp', 'Coun', 'Coll', 'V-sh', 'Vpre', 'Supr', 'Qual', 'Apro', 'Anum', 'Poss']
    #mystem
    ypartos = ['A', 'ADV', 'ADVPRO', 'ANUM', 'APRO', 'COM', 'CONJ', 'INTJ', 'NUM', 'PART', 'PR', 'S', 'SPRO', 'V'] #
    ytense = ['tense', 'praes',	'inpraes', 'praet']
    ycase = ['cas', 'nom', 'gen',	'dat', 'acc', 'ins', 'abl', 'part', 'loc', 'voc']
    ynum = ['number', 'sg', 'pl']
    yverb = ['verb', 'ger', 'inf', 'partcp', 'indic', 'imper']
    yform = ['forma', 'brev', 'plen', 'poss']
    ycomp = ['comp', 'supr', 'comp']
    yperson = ['person', '1p', '2p', '3p']
    ygender = ['gender', 'm', 'f', 'n']
    yaspect = ['aspect', 'ipf', 'pf']
    yvoice = ['voice', 'act', 'pass']
    yanim = ['anim', 'anim', 'inan']
    ytrans = ['trans', 'tran', 'intr']
    yother = ['other', 'parenth', 'geo', 'awkw', 'persn', 'dist', 'mf', 'obsc', 'patrn', 'praed', 'inform', 'rare', 'abbr', 'obsol', 'famn']
    all_parts = [ytense, ycase, ynum, yverb, yform, ycomp, yperson, ygender, yaspect, yvoice, yanim, ytrans, yother]
    #return case['case']
#partos, animacy, gender, number, case, aspect, trans, person, tenses, mood, voice, names, style, other, ypartos, ytense, ycase, ynum, yverb, yform, ycomp, yperson, ygender, yaspect, yvoice, yanim, yother, all_parts
